-- 코드
CREATE TABLE CODE (
	CODE_ID TEXT NOT NULL,		-- 코드번호
	QITEM_NUM INTEGER NOT NULL,	-- 문항번호
	CODE_NM TEXT,				-- 코드명
	PRIMARY KEY (CODE_ID, QITEM_NUM),
	FOREIGN KEY (QITEM_NUM) REFERENCES QITEM (QITEM_NUM)
);

-- 문항
CREATE TABLE QITEM (
	QITEM_NUM INTEGER NOT NULL,	-- 문항번호
	QITEM_NM TEXT,				-- 문항명
	PRIMARY KEY (QITEM_NUM)
);

-- 만족도
CREATE TABLE DGSTFN (
	RSPDNT_ID TEXT NOT NULL,	-- 응답자ID
	Q1 INTEGER,
	Q2 INTEGER,
	Q3 INTEGER,
	Q4 INTEGER,
	Q5 INTEGER,
	Q6 INTEGER,
	Q7 INTEGER,
	Q8 INTEGER,
	PRIMARY KEY (RSPDNT_ID)
);
