CREATE TABLE CODE (
	CODE_ID TEXT NOT NULL,
	QITEM_NUM INTEGER NOT NULL,
	CODE_NM TEXT,
	PRIMARY KEY (CODE_ID, QITEM_NUM),
	FOREIGN KEY (QITEM_NUM) REFERENCES QITEM (QITEM_NUM)
);

CREATE TABLE QITEM (
	QITEM_NUM INTEGER NOT NULL,
	QITEM_NM TEXT,
	PRIMARY KEY (QITEM_NUM)
);

CREATE TABLE DGSTFN (
	RSPDNT_ID TEXT NOT NULL,
	Q1 INTEGER,
	Q2 INTEGER,
	Q3 INTEGER,
	Q4 INTEGER,
	Q5 INTEGER,
	Q6 INTEGER,
	Q7 INTEGER,
	Q8 INTEGER,
	PRIMARY KEY (RSPDNT_ID)
);
